language: php

php:
  - 5.5
  - 5.6
  - 7.0

sudo: false

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
  - phpunit
